### PR TITLE
add script to track primary display brightness

### PR DESCRIPTION
**Pull request by ppannuto**
This tool was a super exciting discovery -- thanks for writing it!

I threw together a quick script to have my external monitor(s) track the primary display, which is controlled automatically by OS X. There wasn't an immediately obvious mechanism other than polling for this, but I found 100ms was responsive enough that the external displays moved in clean steps.

I'm not sure I'd pay the 10Hz process wakeup penalty on my laptop, but nice for the work desktop.

### CODE REVIEW

**Comment by CatalinMustata** [comment]
This can be achieved more easily through IOKit. Reading the data can be done using the following code 
```
CFMutableDictionaryRef matching = IOServiceMatching("IODisplayConnect");
io_service_t displayService = IOServiceGetMatchingService(kIOMasterPortDefault, matching);
float brightness;

while(true) {
    IODisplayGetFloatParameter(displayService, 0, CFSTR(kIODisplayBrightnessKey), &brightness);

    int brightnessLevel = (int)(brightness * 100);
    NSLog(@"Brightness is %d", brightnessLevel);
    usleep(autoSampleRate * SECONDS_TO_USECONDS);
}
```

I'm currently working on developing an auto mode for this, which tracks your main display and sets the externals to match. Polling seems like the easy route for now, but I'm pretty sure I can hook up to the IORegistry and setup a notification handler for the brightness.

**Comment by ppannuto** [comment]
That's awesome! I figured such a thing was possible, I'm just not an OS X developer -- but I can write bash scripts with the best of them :)

Looking forward to what you produce!

**Comment by kfix** [comment]
@ppannuto nifty script! Lemme think on it.

@CatalinMustata: neat idea about hooking on IOReg in the background!
 I'd consider merging a feature resembling `-d 1 --follow-primary -b x<scaling-factor> -c x<scaling-factor>`

**Comment by CatalinMustata** [comment]
I've had a chat with some Apple's MacOS kernel engineers. They weren't able to help me in finding a way to avoid polling - there seems to be a way to get notified about changes, but it's internal and it's not documented for us mere mortals.

One more thing I noticed is that on my 2017 MacBook Pro at least the backlight goes from 0 (completely off) to 100 (eye scorching light). My external Dell has nowhere near as much range, so it needs to be mapped in a way. I'll add this to the menubar app I'm developing as a fork sometime when I get around to it.

**Comment by durandom** [comment]
Have a look at  https://github.com/czarny/Brisync - it does exactly this.

**Comment by sunknudsen** [comment]
@kfix @CatalinMustata Did the conversation die off? I love the idea of a feature allowing `ddcctl` to match the brightness of the built-in display.

**Comment by CatalinMustata** [comment]
I forked @kfix's repo and built a menubar app around it, but I never got around to finishing it - needs a way to match lighting ranges and an improved polling mechanism. Moreover, my current external display works through a DP to USB-C cable and DDC fails silently.

**Comment by kfix** [comment]
I'm glad the ddctl tool was enough to make this script work, but not gonna merge this.

Both Brisync & Lunar do this status polling/subscription more efficiently and should be used for this use case.
I'm not really focusing on the Macbook's screen in this project, perhaps I'm too biased toward the Mini.

The one script/ already in the repo is just an example to show how ddcctl can be used and I don't really want to provide much else that has to be supported.

**Pull request closed without merging**
